version: "3.3"

networks:
  net:
    driver: overlay
    attachable: true
  mon_net:
    external: true

services:
  stress:
    image: progrium/stress
    command: '--cpu 5 --io 2 --vm 3 --vm-bytes 256M --timeout 20s'
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: any
        delay: 5s
        window: 20s
    healthcheck:
      timeout: 10s

  mongo:
    image: healthcheck/mongo:latest
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1

  mongo-exporter:
    image: forekshub/percona-mongodb-exporter:latest
    networks:
      - net
      - mon_net
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
